# Generated by Django 5.2.1 on 2025-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Ranking'),
        ),
    ]
