# Generated by Django 5.2.1 on 2025-05-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.clase'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='clases',
            field=models.ManyToManyField(to='Academico.clase'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.pais'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.ciudad'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='facultad',
            field=models.ManyToManyField(to='Academico.facultad'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.pais'),
        ),
    ]
