# Generated by Django 5.0.3 on 2025-05-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_universidad_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidad',
            name='ranking',
        ),
        migrations.AddField(
            model_name='universidad',
            name='clase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Academico.clase'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='empleabilidad',
            field=models.FloatField(default=0, verbose_name='Valor de Empleabilidad'),
        ),
    ]
