# Generated by Django 5.2.1 on 2025-06-01 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidad',
            name='empleabilidad',
        ),
        migrations.CreateModel(
            name='Empleabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleabilidad', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Valor de Empleabilidad')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.facultad')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.clase')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigacionYDescubrimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacionesPorEscrito', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Citas por Escrito')),
                ('citacionesPorInvestigacion', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Citas por Investigación')),
                ('reputacionAcademica', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='Reputación Académica')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.facultad')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.clase')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.universidad')),
            ],
        ),
    ]
