# Generated by Django 5.0.3 on 2025-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_remove_universidad_ranking_universidad_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoMaterias',
            fields=[
                ('id_conjunto_materias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('clases', models.ManyToManyField(to='Academico.clase', verbose_name='Clases')),
            ],
        ),
    ]
