# Generated by Django 5.2.1 on 2025-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_alter_empleabilidad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleabilidad',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='investigacionydescubrimiento',
            name='materia',
        ),
    ]
