# Generated by Django 5.2.1 on 2025-05-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_conjuntomaterias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Academico.facultad'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConjuntoMaterias',
        ),
    ]
