# Generated by Django 5.2.1 on 2025-05-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_facultad_clase_facultad_delete_conjuntomaterias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultad',
            options={'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='universidad',
        ),
    ]
