# Generated by Django 5.2.1 on 2025-06-03 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_remove_empleabilidad_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Nota'),
        ),
    ]
