# Generated by Django 5.2.1 on 2025-05-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_alter_facultad_options_remove_facultad_universidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='universidad',
            name='clase',
        ),
        migrations.AddField(
            model_name='facultad',
            name='clases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Academico.clase'),
            preserve_default=False,
        ),
    ]
