# Generated by Django 5.2.1 on 2025-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_remove_clase_facultad_remove_universidad_clase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='clases',
        ),
        migrations.AddField(
            model_name='facultad',
            name='clases',
            field=models.ManyToManyField(to='Academico.clase'),
        ),
    ]
