# Generated by Django 5.2.1 on 2025-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0008_remove_facultad_clases_facultad_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='facultad',
            field=models.ManyToManyField(to='Academico.facultad'),
        ),
    ]
